# Generated by Django 4.2 on 2023-04-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_at', models.DateTimeField(auto_now_add=True, verbose_name='대출일')),
                ('return_deadline', models.DateTimeField(verbose_name='반납 기한')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='반납일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='대상 도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대출 사용자')),
            ],
            options={
                'verbose_name': '대출 이력',
                'verbose_name_plural': '대출 이력 목록',
                'db_table': 'book_rentals',
            },
        ),
    ]
