# Generated by Django 4.2 on 2023-04-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowhistory',
            old_name='rent_at',
            new_name='borrowed_at',
        ),
    ]
