# Generated by Django 4.2 on 2023-04-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrow', '0002_rename_rent_at_borrowhistory_borrowed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowhistory',
            old_name='return_at',
            new_name='returned_at',
        ),
    ]
