# Generated by Django 4.2 on 2023-04-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('published_at', models.DateField(verbose_name='출간일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='저자')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서 목록',
                'db_table': 'books',
            },
        ),
    ]
