# Generated by Django 4.2 on 2023-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('description', models.TextField(verbose_name='저자 소개')),
            ],
            options={
                'verbose_name': '저자',
                'verbose_name_plural': '저자 목록',
                'db_table': 'authors',
            },
        ),
    ]
